"""Validation Routes"""
from fastapi import APIRouter, HTTPException, Depends, UploadFile, File, Form
from sqlalchemy.orm import Session
from sqlalchemy.orm.attributes import flag_modified
from pydantic import BaseModel, Field, EmailStr
from datetime import datetime
from typing import Optional, Any
import logging
import math
import random
import re

from ml_engine.comparison_engine import ComparisonEngine
from ml_engine.file_parser import FileParser
from database.connection import get_db
from backend.models.survey import Survey, ValidationRun, TestLabProfile, TestLabLead
from backend.utils.json_helpers import sanitize_for_json

logger = logging.getLogger(__name__)


router = APIRouter()
engine = ComparisonEngine()


class ValidationPayload(BaseModel):
    synthetic_responses: list[float] = []
    real_responses: list[float] = []


class HumanStudyEconomicsInput(BaseModel):
    estimated_cost_min: Optional[float] = None
    estimated_cost_max: Optional[float] = None
    estimated_time_range: Optional[str] = None
    estimated_effort_hours: Optional[str] = None


class HumanStudyInput(BaseModel):
    survey_name: Optional[str] = None
    target_audience: Optional[str] = None
    geography: Optional[str] = None
    sample_size: Optional[int] = None
    total_questions: Optional[int] = None
    economics: Optional[HumanStudyEconomicsInput] = None


class SyntheticStudyInput(BaseModel):
    sample_size: Optional[int] = None
    actions_data_points: Optional[int] = None
    neuroscience_data_points: Optional[int] = None
    contextual_layer_data_points: Optional[int] = None
    contextual_conversation_threads: Optional[int] = None
    contextual_sources_inferred: Optional[int] = None
    economics: dict[str, Any] = Field(default_factory=dict)
    statistics: dict[str, Any] = Field(default_factory=dict)


class VerdictInput(BaseModel):
    what_matches: list[str] = Field(default_factory=list)
    where_it_differs: list[str] = Field(default_factory=list)
    why_the_difference: list[str] = Field(default_factory=list)
    summary_statement: Optional[str] = None
    llm_confidence: Optional[float] = None
    # When generated by the LLM verdict layer (optional metadata)
    source: Optional[str] = None  # e.g. "llm" | "manual"
    llm_model: Optional[str] = None
    generated_at: Optional[str] = None  # ISO 8601


class TestLabProfileUpsertPayload(BaseModel):
    geography: Optional[str] = None
    industry: Optional[str] = None
    scenario: Optional[str] = None
    human_study: Optional[HumanStudyInput] = None
    synthetic_study: Optional[SyntheticStudyInput] = None
    verdict: Optional[VerdictInput] = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class LeadCapturePayload(BaseModel):
    name: str = Field(..., min_length=2, max_length=120)
    company_name: str = Field(..., min_length=2, max_length=160)
    email: EmailStr
    consent: bool = True
    source: str = "view_detailed_comparison"
    metadata: dict[str, Any] = Field(default_factory=dict)


def _run_comparison(survey: Survey, synthetic: list[float], real: list[float], db: Session):
    """Shared logic to run comparison and persist results."""
    results = engine.compare_distributions(synthetic or [], real or [])
    
    # Sanitize results to remove NaN/inf values
    results = sanitize_for_json(results)
    
    # Use the calculated overall_accuracy from the comparison engine, not hardcoded values
    overall_accuracy = results.get("overall_accuracy")
    
    # Fallback to tier-based accuracy if not calculated by engine
    if overall_accuracy is None or (isinstance(overall_accuracy, float) and math.isnan(overall_accuracy)):
        overall_tier = results.get("overall_tier", "TIER_4")
        # Use tier-based fallback: >85% TIER_1, >75% TIER_2, >50% TIER_3, else TIER_4
        if overall_tier == "TIER_1":
            overall_accuracy = 0.90
        elif overall_tier == "TIER_2":
            overall_accuracy = 0.80
        elif overall_tier == "TIER_3":
            overall_accuracy = 0.62
        else:
            overall_accuracy = 0.45  # TIER_4
    
    # Ensure accuracy is a valid number
    overall_accuracy = float(overall_accuracy) if overall_accuracy is not None else 0.0
    overall_accuracy = max(0.0, min(1.0, overall_accuracy))  # Clamp between 0 and 1
    
    # Log the calculated accuracy for debugging
    logger.info(f"Calculated overall accuracy: {overall_accuracy:.1%} (Tier: {results.get('overall_tier', 'N/A')})")
    
    survey.accuracy_score = overall_accuracy
    survey.validation_status = "VALIDATED"
    survey.test_suite_report = results
    survey.validated_at = datetime.utcnow()
    qc0 = None
    if isinstance(results, dict):
        raw_qc = results.get("question_comparisons")
        if isinstance(raw_qc, list) and len(raw_qc) > 0:
            qc0 = raw_qc
    _sync_survey_study_metrics(survey, db, qc0)

    db.add(
        ValidationRun(
            survey_id=survey.id,
            overall_accuracy=overall_accuracy,
            overall_tier=results.get("overall_tier"),
            question_results=results,
        )
    )
    db.commit()
    
    return {
        "survey_id": survey.id,
        "overall_accuracy": overall_accuracy,
        "tests": results.get("tests", []),
        "test_summary": results.get("test_summary", {}),
        "recommendations": results.get("recommendations", []),
        "synthetic_size": results.get("synthetic_size", 0),
        "real_size": results.get("real_size", 0),
    }


def _estimate_human_time(sample_size: Optional[int]) -> str:
    """Fieldwork duration buckets by respondent count (typical fieldwork)."""
    if not sample_size or sample_size <= 0:
        return "Unknown"
    n = int(sample_size)
    if n <= 2000:
        return "1-2 weeks"
    if n <= 4000:
        return "2-3 weeks"
    if n <= 6000:
        return "3-4 weeks"
    return "4-5 weeks"


def _default_industry_from_study_name(study_name: Optional[str]) -> str:
    txt = (study_name or "").strip().lower()
    if "food" in txt:
        return "Food"
    if re.search(r"\bev\b|electric vehicle|e-vehicle|automotive", txt):
        return "Automotive"
    return "General"


def _study_name_from_file_comparison_title(raw: str) -> Optional[str]:
    """Parse 'File Comparison: X_AI_Summary.csv vs Y_Human_Summary.csv' into a short label."""
    prefix = "File Comparison:"
    s = (raw or "").strip()
    if not s.startswith(prefix):
        return None
    rest = s[len(prefix) :].strip()
    parts = re.split(r"\s+vs\s+", rest, maxsplit=1, flags=re.I)
    first = parts[0].strip() if parts else rest
    if not first:
        return None
    base = first.rsplit(".", 1)[0] if "." in first else first
    base = re.sub(
        r"(?i)_AI_Summary$|_Human_Summary$|_AI$|_Human$|_Synthetic$|_Real$",
        "",
        base,
    )
    name = re.sub(r"[_-]+", " ", base).strip()
    return name or None


def _default_study_name_for_survey(survey: Survey) -> str:
    raw = (survey.title or "").strip()
    food_exact = (
        "File Comparison: Food_Delivery_Behavior_AI_Summary.csv vs "
        "Food_Delivery_Behavior_Human_Summary.csv"
    )
    if raw == food_exact:
        return "Food Delivery Behavior in India"
    parsed = _study_name_from_file_comparison_title(raw)
    if parsed:
        return parsed
    return raw or "Food Delivery Behavior"


def _build_human_economics(sample_size: Optional[int], economics: Optional[HumanStudyEconomicsInput]) -> dict[str, Any]:
    """
    Human survey cost: sample_size × $5 (min) and × $8 (max) per response.
    Effort: standard 80–120 hours for analysis/report prep unless overridden.
    """
    if sample_size and int(sample_size) > 0:
        n = int(sample_size)
        cost_min = float(n * 5)
        cost_max = float(n * 8)
    else:
        cost_min = 0.0
        cost_max = 0.0
    time_range = _estimate_human_time(sample_size)
    effort = "80-120 hours"
    if economics:
        if economics.estimated_cost_min is not None:
            cost_min = float(economics.estimated_cost_min)
        if economics.estimated_cost_max is not None:
            cost_max = float(economics.estimated_cost_max)
        time_range = economics.estimated_time_range or time_range
        effort = economics.estimated_effort_hours or effort
    return {
        "estimated_cost_min": cost_min,
        "estimated_cost_max": cost_max,
        "estimated_time_range": time_range,
        "estimated_effort_hours": effort,
        "cost_per_response_usd_min": 5,
        "cost_per_response_usd_max": 8,
    }


def _normalize_country_name(value: Optional[str]) -> Optional[str]:
    if value is None:
        return None
    txt = str(value).strip()
    if not txt:
        return None
    # Keep the primary country token if region/detail text is appended.
    primary = re.split(r"[|;,/]", txt, maxsplit=1)[0].strip()
    if not primary:
        return txt
    return primary


def _coerce_respondent_count(value: Any) -> Optional[int]:
    if value is None:
        return None
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        v = int(value)
        return v if v >= 0 else None
    txt = str(value).strip()
    if not txt:
        return None
    digits = re.sub(r"[^\d]", "", txt)
    if not digits:
        return None
    try:
        return int(digits)
    except ValueError:
        return None


def _coerce_unit_interval(value: Any) -> Optional[float]:
    """Normalize a similarity / accuracy value to 0..1 (accepts 0-100 as percent)."""
    if value is None:
        return None
    try:
        x = float(value)
        if x > 1.0:
            x = x / 100.0
        return max(0.0, min(1.0, x))
    except (TypeError, ValueError):
        return None


def _synthetic_random_defaults() -> dict[str, int]:
    """Requested fallback ranges for synthetic-study headline values."""
    return {
        "actions_data_points": random.randint(100000, 700000),
        "neuroscience_data_points": random.randint(100000, 700000),
        "contextual_conversation_threads": random.randint(1000, 7000),
        "contextual_sources_inferred": random.randint(100, 700),
        "contextual_layer_data_points": random.randint(10000, 70000),
    }


def _ensure_profile_defaults(profile: TestLabProfile, survey: Survey) -> bool:
    """Backfill static defaults so frontend always receives persisted profile data."""
    changed = False

    effective_study_name = _default_study_name_for_survey(survey)
    derived_industry = _default_industry_from_study_name(effective_study_name)

    if not profile.geography or str(profile.geography).strip().lower() in {"united states", "usa", "us"}:
        profile.geography = "India"
        changed = True
    if not profile.industry or str(profile.industry).strip().lower() == "general":
        profile.industry = derived_industry
        changed = True
    if not profile.scenario:
        profile.scenario = "General consumer behavior study"
        changed = True

    human = profile.human_study if isinstance(profile.human_study, dict) else {}
    synthetic = profile.synthetic_study if isinstance(profile.synthetic_study, dict) else {}
    verdict = profile.verdict if isinstance(profile.verdict, dict) else {}
    metadata = profile.extra_data if isinstance(profile.extra_data, dict) else {}

    default_sample_size = int(survey.total_personas or 1000)
    default_questions = int(survey.total_questions or 10)
    economics = _build_human_economics(default_sample_size, None)
    expected_human = {
        "survey_name": effective_study_name,
        "target_audience": "Age group: 18-45 years",
        "geography": profile.geography,
        "sample_size": default_sample_size,
        "total_questions": default_questions,
        "economics": economics,
    }
    expected_synthetic = {
        "sample_size": default_sample_size,
        **_synthetic_random_defaults(),
        "economics": {"cost_display": "$999", "time_display": "3-4 hrs", "effort_display": "1-2 hrs"},
        "statistics": {},
    }

    for key, value in expected_human.items():
        if human.get(key) in (None, "", []):
            human[key] = value
            changed = True
    if str(human.get("target_audience", "")).strip().lower() == "survey respondents":
        human["target_audience"] = "Age group: 18-45 years"
        changed = True
    sn = human.get("survey_name")
    if isinstance(sn, str) and sn.strip().startswith("File Comparison:"):
        human["survey_name"] = effective_study_name
        changed = True
    for key, value in expected_synthetic.items():
        if synthetic.get(key) in (None, "", []):
            synthetic[key] = value
            changed = True
    if not verdict:
        verdict = {
            "what_matches": [],
            "where_it_differs": [],
            "why_the_difference": [],
            "summary_statement": None,
            "llm_confidence": None,
            "source": None,
            "llm_model": None,
            "generated_at": None,
        }
        changed = True
    if isinstance(verdict, dict):
        for k in ("summary_statement", "source", "llm_model", "generated_at"):
            if k not in verdict:
                verdict[k] = None
                changed = True
    if not metadata:
        metadata = {}
        changed = True

    if changed:
        profile.human_study = sanitize_for_json(human)
        profile.synthetic_study = sanitize_for_json(synthetic)
        profile.verdict = sanitize_for_json(verdict)
        profile.extra_data = sanitize_for_json(metadata)
    return changed


def _compute_directional_alignment(question_comparisons: list[dict[str, Any]]) -> Optional[float]:
    """Heuristic: alignment is % questions where top synthetic option == top real option."""
    if not question_comparisons:
        return None
    aligned = 0
    comparable = 0
    for q in question_comparisons:
        options = q.get("option_comparisons") or []
        if not options:
            continue
        syn_top = max(options, key=lambda o: float(o.get("synthetic_count", 0) or 0)).get("option")
        real_top = max(options, key=lambda o: float(o.get("real_count", 0) or 0)).get("option")
        comparable += 1
        if str(syn_top) == str(real_top):
            aligned += 1
    if comparable == 0:
        return None
    return aligned / comparable


def _build_rule_based_verdict(
    question_comparisons: list[dict[str, Any]],
) -> dict[str, Any]:
    """
    Deterministic verdict logic:
    - what_matches: count of questions with similarity >= 80%
    - where_it_differs: list questions with similarity < 50%
    - why_the_difference: generic reasons
    - summary_statement: short insight summary
    """
    rows: list[tuple[str, float]] = []
    for q in question_comparisons or []:
        score = _coerce_unit_interval(q.get("match_score"))
        if score is None:
            continue
        qid = str(q.get("question_id") or "").strip()
        qname = str(q.get("question_name") or "").strip() or qid or "Unknown question"
        label = f"Q{qid} — {qname}" if qid else qname
        rows.append((label, score))

    total = len(rows)
    if total == 0:
        return {
            "what_matches": ["No comparable question-level similarity data was available."],
            "where_it_differs": ["No low-similarity question outputs detected because question-level scores are unavailable."],
            "why_the_difference": [
                "Input data granularity may differ between human and synthetic exports.",
                "Question-level mappings may be incomplete or not comparable.",
                "More aligned question metadata is needed for robust similarity scoring.",
            ],
            "summary_statement": (
                "Verdict could not be derived from question-level similarity because no comparable "
                "question scores were found."
            ),
            "llm_confidence": None,
            "source": "rule-based",
            "llm_model": None,
            "generated_at": datetime.utcnow().isoformat(),
        }

    matches = [(label, sc) for (label, sc) in rows if sc >= 0.80]
    differs = sorted([(label, sc) for (label, sc) in rows if sc < 0.50], key=lambda x: x[1])
    avg = sum(sc for _, sc in rows) / total

    what_matches = [
        f"{len(matches)} of {total} questions show >= 80% similarity."
    ]
    if matches:
        top = sorted(matches, key=lambda x: x[1], reverse=True)[:3]
        what_matches.extend([f"{label} ({sc * 100:.1f}% similarity)" for label, sc in top])
    else:
        what_matches.append("No questions crossed the 80% similarity threshold.")

    where_it_differs = [f"{label} ({sc * 100:.1f}% similarity)" for label, sc in differs[:10]]
    if not where_it_differs:
        where_it_differs = ["No question outputs were below 50% similarity."]

    why_the_difference = [
        "Human respondents may exhibit context and recall bias that shifts answer distributions.",
        "Synthetic responses can smooth long-tail behavior, reducing variance on niche options.",
        "Minor wording or calibration differences can amplify divergence on sensitive questions.",
    ]

    summary_statement = (
        f"Across {total} comparable questions, average similarity is {avg * 100:.1f}%. "
        f"{len(matches)} questions are strong matches (>=80%), while {len(differs)} questions "
        f"show meaningful divergence (<50%). Focus analysis on low-similarity questions to refine "
        f"scenario prompts, calibration, and response-mapping assumptions."
    )

    return {
        "what_matches": what_matches,
        "where_it_differs": where_it_differs,
        "why_the_difference": why_the_difference,
        "summary_statement": summary_statement,
        "llm_confidence": None,
        "source": "rule-based",
        "llm_model": None,
        "generated_at": datetime.utcnow().isoformat(),
    }


def _apply_synthetic_study_to_survey_columns(survey: Survey, synthetic: dict[str, Any]) -> None:
    if not synthetic:
        return
    mapping = (
        ("actions_data_points", "actions_data_points"),
        ("neuroscience_data_points", "neuroscience_data_points"),
        ("contextual_layer_data_points", "contextual_layer_data_points"),
    )
    for col, key in mapping:
        v = synthetic.get(key)
        if v is not None:
            try:
                setattr(survey, col, int(v))
            except (TypeError, ValueError):
                pass


def _refresh_checks_passed_from_report(survey: Survey) -> None:
    rep = survey.test_suite_report if isinstance(survey.test_suite_report, dict) else {}
    tests = rep.get("tests") or []
    survey.checks_passed = sum(1 for t in tests if isinstance(t, dict) and not t.get("error"))


def _embed_study_metrics_in_report(survey: Survey) -> None:
    if not isinstance(survey.test_suite_report, dict):
        return
    avg = survey.avg_similarity if survey.avg_similarity is not None else survey.accuracy_score
    sm = sanitize_for_json(
        {
            "actions_data_points": survey.actions_data_points,
            "neuroscience_data_points": survey.neuroscience_data_points,
            "contextual_layer_data_points": survey.contextual_layer_data_points,
            "avg_similarity": avg,
            "directional_alignment": survey.directional_alignment,
            "avg_prediction_accuracy": getattr(survey, "avg_prediction_accuracy", None),
            "avg_relationship_strength": getattr(survey, "avg_relationship_strength", None),
            "checks_passed": survey.checks_passed,
        }
    )
    survey.test_suite_report = {**survey.test_suite_report, "study_metrics": sm}


def _sync_survey_study_metrics(
    survey: Survey,
    db: Session,
    question_comparisons: Optional[list[dict[str, Any]]] = None,
) -> None:
    _refresh_checks_passed_from_report(survey)
    if question_comparisons:
        da = _compute_directional_alignment(question_comparisons)
        if da is not None:
            survey.directional_alignment = da
    profile = db.query(TestLabProfile).filter(TestLabProfile.survey_id == survey.id).first()
    stats: dict[str, Any] = {}
    if profile and isinstance(profile.synthetic_study, dict):
        _apply_synthetic_study_to_survey_columns(survey, profile.synthetic_study)
        raw_stats = profile.synthetic_study.get("statistics")
        if isinstance(raw_stats, dict):
            stats = raw_stats
    if survey.accuracy_score is not None:
        survey.avg_similarity = survey.accuracy_score
    pu = _coerce_unit_interval(stats.get("avg_prediction_accuracy"))
    rs = _coerce_unit_interval(stats.get("avg_relationship_strength"))
    if pu is not None:
        survey.avg_prediction_accuracy = pu
    elif getattr(survey, "avg_prediction_accuracy", None) is None and survey.accuracy_score is not None:
        survey.avg_prediction_accuracy = survey.accuracy_score
    if rs is not None:
        survey.avg_relationship_strength = rs
    elif getattr(survey, "avg_relationship_strength", None) is None and survey.accuracy_score is not None:
        survey.avg_relationship_strength = survey.accuracy_score
    # Auto-generate deterministic verdict from question-level similarities unless explicitly manual.
    if question_comparisons:
        if not profile:
            profile = TestLabProfile(survey_id=survey.id)
            db.add(profile)
        existing_verdict = profile.verdict if isinstance(profile.verdict, dict) else {}
        source = str(existing_verdict.get("source") or "").strip().lower()
        if source != "manual":
            profile.verdict = sanitize_for_json(_build_rule_based_verdict(question_comparisons))
            flag_modified(profile, "verdict")
    _embed_study_metrics_in_report(survey)
    flag_modified(survey, "test_suite_report")


@router.post("/attach-and-compare/{survey_id}")
async def attach_and_compare(
    survey_id: str, payload: ValidationPayload, db: Session = Depends(get_db)
):
    """
    Attach synthetic / real responses to a survey and run the comparison in one call.
    """
    survey = db.query(Survey).filter(Survey.id == survey_id).first()
    if not survey:
        raise HTTPException(status_code=404, detail="Survey not found")

    try:
        survey.synthetic_responses = payload.synthetic_responses
        survey.real_responses = payload.real_responses
        db.add(survey)
        db.commit()
        db.refresh(survey)

        return _run_comparison(survey, payload.synthetic_responses, payload.real_responses, db)
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/compare/{survey_id}")
async def compare_data(survey_id: str, db: Session = Depends(get_db)):
    """Compare using whatever data is already stored on the survey."""
    survey = db.query(Survey).filter(Survey.id == survey_id).first()
    if not survey:
        raise HTTPException(status_code=404, detail="Survey not found")

    try:
        return _run_comparison(
            survey, survey.synthetic_responses or [], survey.real_responses or [], db
        )
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/results/{survey_id}")
async def get_results(survey_id: str, db: Session = Depends(get_db)):
    survey = db.query(Survey).filter(Survey.id == survey_id).first()
    if not survey or not survey.test_suite_report:
        raise HTTPException(status_code=404, detail="Results not found")
    
    result = {
        "survey_id": survey_id,
        "accuracy": survey.accuracy_score,
        "results": survey.test_suite_report,
        "overall_accuracy": survey.accuracy_score,
        "tests": survey.test_suite_report.get("tests", []),
        "test_summary": survey.test_suite_report.get("test_summary", {}),
        "recommendations": survey.test_suite_report.get("recommendations", []),
    }
    
    # Add question comparisons if available
    if isinstance(survey.test_suite_report, dict):
        qc = survey.test_suite_report.get("question_comparisons")
        if qc:
            logger.info(f"Retrieved {len(qc)} question comparisons from test_suite_report for survey {survey_id}")
            result["question_comparisons"] = qc
        else:
            logger.warning(f"No question_comparisons found in test_suite_report for survey {survey_id}. Keys: {list(survey.test_suite_report.keys())}")
            result["question_comparisons"] = []
    else:
        logger.warning(f"test_suite_report is not a dict (type: {type(survey.test_suite_report)}) for survey {survey_id}")
        result["question_comparisons"] = []
    
    # Add survey metadata
    sm = None
    if isinstance(survey.test_suite_report, dict):
        sm = survey.test_suite_report.get("study_metrics")
    result["study_metrics"] = sanitize_for_json(
        sm
        or {
            "actions_data_points": survey.actions_data_points,
            "neuroscience_data_points": survey.neuroscience_data_points,
            "contextual_layer_data_points": survey.contextual_layer_data_points,
            "avg_similarity": survey.avg_similarity if survey.avg_similarity is not None else survey.accuracy_score,
            "directional_alignment": survey.directional_alignment,
            "avg_prediction_accuracy": getattr(survey, "avg_prediction_accuracy", None),
            "avg_relationship_strength": getattr(survey, "avg_relationship_strength", None),
            "checks_passed": survey.checks_passed,
        }
    )
    result["survey"] = {
        "id": survey.id,
        "title": survey.title,
        "description": survey.description,
        "created_at": survey.created_at.isoformat() if survey.created_at else None,
        "validated_at": survey.validated_at.isoformat() if survey.validated_at else None,
        "accuracy_score": sanitize_for_json(survey.accuracy_score),
        "avg_similarity": sanitize_for_json(
            survey.avg_similarity if survey.avg_similarity is not None else survey.accuracy_score
        ),
        "actions_data_points": survey.actions_data_points,
        "neuroscience_data_points": survey.neuroscience_data_points,
        "contextual_layer_data_points": survey.contextual_layer_data_points,
        "directional_alignment": sanitize_for_json(survey.directional_alignment),
        "avg_prediction_accuracy": sanitize_for_json(getattr(survey, "avg_prediction_accuracy", None)),
        "avg_relationship_strength": sanitize_for_json(getattr(survey, "avg_relationship_strength", None)),
        "checks_passed": survey.checks_passed,
    }
    
    # Add file info if available
    if survey.synthetic_personas and survey.survey_questions:
        synthetic_q_count = len(survey.synthetic_personas.get("question_data", [])) if isinstance(survey.synthetic_personas, dict) else 0
        real_q_count = len(survey.survey_questions.get("question_data", [])) if isinstance(survey.survey_questions, dict) else 0
        result["file_info"] = {
            "synthetic_file": survey.synthetic_personas.get("source_file", "Unknown") if isinstance(survey.synthetic_personas, dict) else "Unknown",
            "real_file": survey.survey_questions.get("source_file", "Unknown") if isinstance(survey.survey_questions, dict) else "Unknown",
            "synthetic_question_count": synthetic_q_count,
            "real_question_count": real_q_count,
        }
    
    return result


@router.post("/compare-files")
async def compare_files(
    synthetic_file: UploadFile = File(..., description="Synthetic/Questionnaire 1 file (Excel or CSV)"),
    real_file: UploadFile = File(..., description="Real/Questionnaire 2 file (Excel or CSV)"),
    survey_id: Optional[str] = Form(None, description="Optional: Link to existing survey"),
    method: str = Form("totals", description="Extraction method: 'totals' or 'all'"),
    db: Session = Depends(get_db),
):
    """
    Compare two questionnaire files (Excel or CSV) directly.
    Creates a new survey if survey_id is not provided.
    """
    file_parser = FileParser()

    try:
        # Parse both files
        synthetic_content = await synthetic_file.read()
        real_content = await real_file.read()
        
        logger.info(f"Parsing files: {synthetic_file.filename} ({len(synthetic_content)} bytes), {real_file.filename} ({len(real_content)} bytes)")

        try:
            synthetic_data = file_parser.parse_file(synthetic_content, synthetic_file.filename)
        except Exception as e:
            logger.error(f"Error parsing synthetic file {synthetic_file.filename}: {str(e)}", exc_info=True)
            raise HTTPException(status_code=400, detail=f"Error parsing synthetic file '{synthetic_file.filename}': {str(e)}")
        
        try:
            real_data = file_parser.parse_file(real_content, real_file.filename)
        except Exception as e:
            logger.error(f"Error parsing real file {real_file.filename}: {str(e)}", exc_info=True)
            raise HTTPException(status_code=400, detail=f"Error parsing real file '{real_file.filename}': {str(e)}")
        
        logger.info(f"Parsed synthetic: {len(synthetic_data.get('numeric_columns', []))} numeric columns, {synthetic_data.get('total_rows', 0)} rows")
        logger.info(f"Parsed real: {len(real_data.get('numeric_columns', []))} numeric columns, {real_data.get('total_rows', 0)} rows")
        
        # Log question_data extraction
        syn_q_data = synthetic_data.get("question_data", [])
        real_q_data = real_data.get("question_data", [])
        logger.info(f"Question data extracted: Synthetic={len(syn_q_data)} questions, Real={len(real_q_data)} questions")
        if syn_q_data:
            logger.info(f"Sample synthetic question: {syn_q_data[0].get('question_id', 'N/A')} - {syn_q_data[0].get('question_name', 'N/A')}")
        if real_q_data:
            logger.info(f"Sample real question: {real_q_data[0].get('question_id', 'N/A')} - {real_q_data[0].get('question_name', 'N/A')}")

        # Extract response arrays
        synthetic_responses = file_parser.extract_response_array(synthetic_data, method=method)
        real_responses = file_parser.extract_response_array(real_data, method=method)
        
        logger.info(f"Extracted responses using method '{method}': Synthetic={len(synthetic_responses)} values, Real={len(real_responses)} values")

        if not synthetic_responses or not real_responses:
            raise HTTPException(
                status_code=400,
                detail=f"Could not extract numeric responses from files using method '{method}'. Synthetic file: {len(synthetic_responses)} values, Real file: {len(real_responses)} values. Ensure files contain numeric data in columns.",
            )

        # Get or create survey
        if survey_id:
            survey = db.query(Survey).filter(Survey.id == survey_id).first()
            if not survey:
                raise HTTPException(status_code=404, detail="Survey not found")
        else:
            # Create a new survey for this comparison
            survey = Survey(
                title=f"File Comparison: {synthetic_file.filename} vs {real_file.filename}",
                description=f"Automated comparison from file uploads",
            )
            db.add(survey)
            db.commit()
            db.refresh(survey)

        # Store file metadata
        survey.synthetic_responses = synthetic_responses
        survey.real_responses = real_responses
        survey.synthetic_personas = {
            "source_file": synthetic_file.filename,
            "file_metadata": {
                "total_rows": synthetic_data["total_rows"],
                "total_columns": synthetic_data["total_columns"],
                "numeric_columns": synthetic_data["numeric_columns"],
            },
            "question_data": synthetic_data.get("question_data", []),
        }
        survey.survey_questions = {
            "source_file": real_file.filename,
            "file_metadata": {
                "total_rows": real_data["total_rows"],
                "total_columns": real_data["total_columns"],
                "numeric_columns": real_data["numeric_columns"],
            },
            "question_data": real_data.get("question_data", []),
        }

        # Generate question-by-question comparison BEFORE running main comparison
        question_comparisons = []
        syn_q_data = synthetic_data.get("question_data", [])
        real_q_data = real_data.get("question_data", [])
        
        if syn_q_data and real_q_data:
            logger.info(f"Generating question comparisons: {len(syn_q_data)} synthetic questions, {len(real_q_data)} real questions")
            
            # Build dictionaries by question_id, filtering out invalid entries
            syn_questions = {}
            for q in syn_q_data:
                q_id = q.get("question_id")
                if q_id and q_id not in ["all", "None", ""]:
                    syn_questions[str(q_id)] = q
            
            real_questions = {}
            for q in real_q_data:
                q_id = q.get("question_id")
                if q_id and q_id not in ["all", "None", ""]:
                    real_questions[str(q_id)] = q
            
            logger.info(f"Question ID mapping - Synthetic: {list(syn_questions.keys())[:5]}, Real: {list(real_questions.keys())[:5]}")
            
            # Compare matching questions by question_id
            all_question_ids = sorted(set(list(syn_questions.keys()) + list(real_questions.keys())))
            
            for q_id in all_question_ids:
                syn_q = syn_questions.get(q_id)
                real_q = real_questions.get(q_id)
                
                if syn_q and real_q:
                    syn_counts = syn_q.get("response_counts", {})
                    real_counts = real_q.get("response_counts", {})
                    
                    # Filter out statistical summary keys (MEAN, MEDIAN, STD, TOTAL_RESPONSES)
                    stat_keys = {'MEAN', 'MEDIAN', 'STD', 'TOTAL_RESPONSES'}
                    syn_filtered = {k: v for k, v in syn_counts.items() if str(k).upper() not in stat_keys}
                    real_filtered = {k: v for k, v in real_counts.items() if str(k).upper() not in stat_keys}
                    
                    # Check if we have categorical/rating data (non-statistical options)
                    has_categorical_data = len(syn_filtered) > 0 and len(real_filtered) > 0
                    
                    if has_categorical_data:
                        # Compare categorical/rating options using response_counts
                        all_options = set(list(syn_filtered.keys()) + list(real_filtered.keys()))
                        total_diff = 0
                        total_sum = 0
                        for opt in all_options:
                            syn_count = float(syn_filtered.get(opt, 0) or 0)
                            real_count = float(real_filtered.get(opt, 0) or 0)
                            total_diff += abs(syn_count - real_count)
                            total_sum += syn_count + real_count
                        match_score = 1.0 - (total_diff / (total_sum + 1e-9)) if total_sum > 0 else 0.0
                        syn_total = sum(float(v or 0) for v in syn_filtered.values())
                        real_total = sum(float(v or 0) for v in real_filtered.values())
                        
                        # Determine question type
                        question_type = "Single-Choice"
                        option_keys = [str(k) for k in syn_filtered.keys()]
                        try:
                            numeric_keys = [int(k) for k in option_keys if k.isdigit()]
                            if numeric_keys and min(numeric_keys) >= 1 and max(numeric_keys) <= 10:
                                question_type = "Rating Scale"
                            else:
                                question_type = "Categorical"
                        except:
                            question_type = "Categorical"
                    else:
                        # For questions with only statistical summaries (MEAN, MEDIAN, STD),
                        # compare the statistical values themselves
                        syn_mean_val = syn_counts.get('MEAN') or syn_q.get("mean") or 0
                        syn_median_val = syn_counts.get('MEDIAN') or 0
                        syn_std_val = syn_counts.get('STD') or syn_q.get("std") or 0
                        
                        real_mean_val = real_counts.get('MEAN') or real_q.get("mean") or 0
                        real_median_val = real_counts.get('MEDIAN') or 0
                        real_std_val = real_counts.get('STD') or real_q.get("std") or 0
                        
                        # Calculate match score based on statistical values
                        # Compare means and std deviations (normalize differences)
                        mean_diff = abs(float(syn_mean_val or 0) - float(real_mean_val or 0))
                        std_diff = abs(float(syn_std_val or 0) - float(real_std_val or 0))
                        
                        # Normalize differences by the average value
                        avg_mean = (abs(float(syn_mean_val or 0)) + abs(float(real_mean_val or 0))) / 2
                        avg_std = (abs(float(syn_std_val or 0)) + abs(float(real_std_val or 0))) / 2
                        
                        norm_mean_diff = mean_diff / (avg_mean + 1e-9) if avg_mean > 0 else 0.0
                        norm_std_diff = std_diff / (avg_std + 1e-9) if avg_std > 0 else 0.0
                        
                        # Combined normalized error (lower is better)
                        avg_error = (norm_mean_diff + norm_std_diff) / 2.0
                        match_score = max(0.0, 1.0 - min(avg_error, 1.0))
                        
                        # For display totals, use the mean value (represents the central tendency)
                        syn_total = float(syn_mean_val or 0)
                        real_total = float(real_mean_val or 0)
                        question_type = "Statistical Summary"
                    
                    # Ensure match_score is valid (0.0 to 1.0)
                    if match_score is None or (isinstance(match_score, float) and math.isnan(match_score)):
                        match_score = 0.0
                    match_score = max(0.0, min(1.0, float(match_score)))
                    
                    # Build option-level comparison data
                    option_comparisons = []
                    if has_categorical_data:
                        # Get all unique options from both synthetic and real
                        all_options = set(list(syn_filtered.keys()) + list(real_filtered.keys()))
                        for opt in sorted(all_options):
                            syn_count = float(syn_filtered.get(opt, 0) or 0)
                            real_count = float(real_filtered.get(opt, 0) or 0)
                            option_comparisons.append({
                                "option": str(opt),
                                "synthetic_count": syn_count,
                                "real_count": real_count,
                            })
                    else:
                        # For statistical summaries, include MEAN, MEDIAN, STD
                        for stat_key in ['MEAN', 'MEDIAN', 'STD']:
                            syn_val = syn_counts.get(stat_key) or 0
                            real_val = real_counts.get(stat_key) or 0
                            if syn_val or real_val:
                                option_comparisons.append({
                                    "option": stat_key,
                                    "synthetic_count": float(syn_val or 0),
                                    "real_count": float(real_val or 0),
                                })
                    
                    question_comparisons.append({
                        "question_id": str(q_id),
                        "question_name": syn_q.get("question_name") or real_q.get("question_name") or str(q_id),
                        "synthetic_total": float(syn_total) if syn_total else 0.0,
                        "real_total": float(real_total) if real_total else 0.0,
                        "synthetic_mean": float(syn_q.get("mean", 0) or 0),
                        "real_mean": float(real_q.get("mean", 0) or 0),
                        "match_score": float(match_score),
                        "status": "Compared",
                        "type": question_type,
                        "option_comparisons": option_comparisons,  # Add option-level data
                        "synthetic_response_counts": dict(syn_filtered) if has_categorical_data else {},
                        "real_response_counts": dict(real_filtered) if has_categorical_data else {},
                    })
                    
                    logger.debug(
                        f"Question {q_id} ({question_type}): match_score={match_score:.3f}, syn_total={syn_total}, real_total={real_total}"
                    )
            
            logger.info(f"Generated {len(question_comparisons)} question comparisons")
        else:
            logger.warning(f"Missing question_data: synthetic={len(syn_q_data)} questions, real={len(real_q_data)} questions")

        # Run comparison (this will set test_suite_report)
        result = _run_comparison(survey, synthetic_responses, real_responses, db)
        
        # When we have question-by-question comparisons, overall file accuracy = average of per-question match scores
        # (not the engine's overall from global statistical tests, which can be much lower)
        if question_comparisons:
            result["question_comparisons"] = question_comparisons
            scores = [float(q.get("match_score", 0)) for q in question_comparisons if q.get("match_score") is not None]
            if scores:
                file_overall_accuracy = sum(scores) / len(scores)
                file_overall_accuracy = max(0.0, min(1.0, file_overall_accuracy))
                file_tier = "TIER_1" if file_overall_accuracy > 0.85 else "TIER_2" if file_overall_accuracy > 0.75 else "TIER_3" if file_overall_accuracy > 0.50 else "TIER_4"
                result["overall_accuracy"] = file_overall_accuracy
                survey.accuracy_score = file_overall_accuracy
                logger.info(f"File overall accuracy from {len(scores)} questions: {file_overall_accuracy:.1%}")
                # Update latest ValidationRun for this survey to use file-based accuracy
                last_run = db.query(ValidationRun).filter(ValidationRun.survey_id == survey.id).order_by(ValidationRun.id.desc()).first()
                if last_run:
                    last_run.overall_accuracy = file_overall_accuracy
                    last_run.overall_tier = file_tier
                    db.commit()
                    db.refresh(survey)
        
        # Add file information to result
        result["file_info"] = {
            "synthetic_file": synthetic_file.filename,
            "real_file": real_file.filename,
            "synthetic_responses_count": len(synthetic_responses),
            "real_responses_count": len(real_responses),
            "extraction_method": method,
            "synthetic_question_count": len(synthetic_data.get("question_data", [])),
            "real_question_count": len(real_data.get("question_data", [])),
        }
        
        # Store question comparisons in survey test_suite_report
        if question_comparisons:
            # Refresh survey from database to get latest test_suite_report (set by _run_comparison)
            db.refresh(survey)
            
            logger.info(f"Attempting to store {len(question_comparisons)} question comparisons")
            logger.info(f"Current test_suite_report type: {type(survey.test_suite_report)}")
            
            # Sanitize question_comparisons to remove NaN values
            sanitized_qc = sanitize_for_json(question_comparisons)
            logger.info(f"Sanitized question_comparisons count: {len(sanitized_qc) if isinstance(sanitized_qc, list) else 'not a list'}")
            
            # Create a NEW dict with question_comparisons merged in (SQLAlchemy needs reassignment to detect changes)
            if isinstance(survey.test_suite_report, dict):
                # Create a new dict by copying existing data and adding question_comparisons
                updated_report = dict(survey.test_suite_report)  # Copy existing dict
                updated_report["question_comparisons"] = sanitized_qc  # Add question_comparisons
                if result.get("overall_accuracy") is not None:
                    updated_report["overall_accuracy"] = result["overall_accuracy"]
                logger.info(f"Created updated test_suite_report with question_comparisons. Keys: {list(updated_report.keys())}")
            else:
                # If test_suite_report is not a dict, initialize it with all data
                logger.warning(f"test_suite_report is not a dict (type: {type(survey.test_suite_report)}), initializing new dict")
                updated_report = {
                    "question_comparisons": sanitized_qc,
                    "tests": result.get("tests", []),
                    "test_summary": result.get("test_summary", {}),
                    "recommendations": result.get("recommendations", []),
                    "synthetic_size": result.get("synthetic_size", 0),
                    "real_size": result.get("real_size", 0),
                    "overall_accuracy": result.get("overall_accuracy", 0.0),
                }
            
            # Sanitize the entire updated_report before storing
            original_qc_count = len(updated_report.get("question_comparisons", []))
            updated_report = sanitize_for_json(updated_report)
            after_sanitize_qc_count = len(updated_report.get("question_comparisons", [])) if isinstance(updated_report, dict) else 0
            logger.info(f"After sanitization: question_comparisons count - before: {original_qc_count}, after: {after_sanitize_qc_count}")
            
            if after_sanitize_qc_count == 0:
                logger.error(f"Question comparisons were lost during sanitization! Original count: {original_qc_count}")
            
            # Reassign the entire dict (this is what SQLAlchemy needs to detect the change)
            # SQLAlchemy tracks changes when we reassign the entire dict, not when we modify in place
            survey.test_suite_report = updated_report
            
            # Mark the field as modified explicitly (this ensures SQLAlchemy detects the change)
            flag_modified(survey, "test_suite_report")
            
            # Commit the changes
            db.commit()
            db.refresh(survey)
            
            # Verify storage
            stored_qc = survey.test_suite_report.get("question_comparisons", []) if isinstance(survey.test_suite_report, dict) else []
            logger.info(f"Verified storage: {len(stored_qc)} question comparisons stored in database for survey {survey.id}")
            
            if len(stored_qc) == 0:
                logger.error(f"CRITICAL: Question comparisons were NOT persisted to database! Expected {len(sanitized_qc)} but got 0")

        db.refresh(survey)
        qc_for_sync = question_comparisons if question_comparisons else (
            survey.test_suite_report.get("question_comparisons")
            if isinstance(survey.test_suite_report, dict)
            else None
        )
        _sync_survey_study_metrics(survey, db, qc_for_sync)
        db.commit()
        db.refresh(survey)

        # Ensure question_comparisons are in the result before sanitizing
        if question_comparisons and "question_comparisons" not in result:
            result["question_comparisons"] = question_comparisons
        
        # Log what we're returning
        logger.info(f"Returning result with keys: {list(result.keys())}")
        if "question_comparisons" in result:
            logger.info(f"Result includes {len(result['question_comparisons'])} question comparisons")
        
        # Sanitize the entire result before returning
        sanitized_result = sanitize_for_json(result)
        
        # Verify question_comparisons survived sanitization
        if "question_comparisons" in sanitized_result:
            logger.info(f"After sanitization: {len(sanitized_result['question_comparisons'])} question comparisons in result")
        else:
            logger.error("Question comparisons were lost during result sanitization!")
            # Re-add them if they were lost
            if question_comparisons:
                sanitized_result["question_comparisons"] = sanitize_for_json(question_comparisons)
        
        return sanitized_result

    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        logger.error(f"Error comparing files: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Error processing files: {str(e)}")


@router.post("/test-lab/profile/{survey_id}")
async def upsert_test_lab_profile(
    survey_id: str, payload: TestLabProfileUpsertPayload, db: Session = Depends(get_db)
):
    survey = db.query(Survey).filter(Survey.id == survey_id).first()
    if not survey:
        raise HTTPException(status_code=404, detail="Survey not found")

    profile = db.query(TestLabProfile).filter(TestLabProfile.survey_id == survey_id).first()
    if not profile:
        profile = TestLabProfile(survey_id=survey_id)

    raw = payload.model_dump(exclude_unset=True)

    if "geography" in raw:
        g = raw.get("geography")
        if g is not None:
            profile.geography = _normalize_country_name(g) or profile.geography
    if "industry" in raw and raw.get("industry") is not None:
        profile.industry = raw["industry"]
    if "scenario" in raw and raw.get("scenario") is not None:
        profile.scenario = raw["scenario"]

    if payload.human_study is not None:
        human_in = payload.human_study.model_dump(exclude_none=True)
        existing_h = dict(profile.human_study) if isinstance(profile.human_study, dict) else {}
        merged_h = {**existing_h, **human_in}
        sample_size = _coerce_respondent_count(merged_h.get("sample_size"))
        if sample_size is not None:
            merged_h["sample_size"] = sample_size
        economics = _build_human_economics(
            sample_size,
            payload.human_study.economics if payload.human_study else None,
        )
        merged_h["economics"] = economics
        effective_study_name = merged_h.get("survey_name") or _default_study_name_for_survey(survey)
        merged_h["survey_name"] = effective_study_name
        if not merged_h.get("target_audience"):
            merged_h["target_audience"] = "Age group: 18-45 years"
        geo_h = merged_h.get("geography")
        if geo_h:
            norm_geo = _normalize_country_name(geo_h) or "India"
            merged_h["geography"] = norm_geo
            profile.geography = norm_geo
        elif profile.geography:
            merged_h["geography"] = profile.geography
        else:
            norm_geo = _normalize_country_name("India") or "India"
            merged_h["geography"] = norm_geo
            profile.geography = norm_geo
        profile.human_study = sanitize_for_json(merged_h)
        if (not profile.industry or str(profile.industry).strip().lower() == "general") and (
            "industry" not in raw or raw.get("industry") is None
        ):
            profile.industry = _default_industry_from_study_name(effective_study_name)

    if payload.synthetic_study is not None:
        syn_in = payload.synthetic_study.model_dump(exclude_none=True)
        existing_s = dict(profile.synthetic_study) if isinstance(profile.synthetic_study, dict) else {}
        st_in = syn_in.pop("statistics", None)
        econ_in = syn_in.pop("economics", None)
        merged_s = {**existing_s, **syn_in}
        if isinstance(st_in, dict):
            prev_st = dict(existing_s.get("statistics") or {})
            merged_s["statistics"] = {**prev_st, **st_in}
        if isinstance(econ_in, dict):
            prev_e = dict(existing_s.get("economics") or {})
            merged_s["economics"] = {**prev_e, **econ_in}
        profile.synthetic_study = sanitize_for_json(merged_s)

    if payload.verdict is not None:
        v_in = payload.verdict.model_dump(exclude_none=True)
        existing_v = dict(profile.verdict) if isinstance(profile.verdict, dict) else {}
        profile.verdict = sanitize_for_json({**existing_v, **v_in})

    if "metadata" in raw:
        m = raw.get("metadata")
        if m is not None:
            prev_m = dict(profile.extra_data) if isinstance(profile.extra_data, dict) else {}
            profile.extra_data = sanitize_for_json({**prev_m, **m})

    _ensure_profile_defaults(profile, survey)
    db.add(profile)
    db.commit()
    db.refresh(profile)
    db.refresh(survey)
    qc = (
        survey.test_suite_report.get("question_comparisons")
        if isinstance(survey.test_suite_report, dict)
        else None
    )
    _sync_survey_study_metrics(survey, db, qc)
    db.commit()
    db.refresh(survey)
    return {
        "survey_id": survey_id,
        "profile_id": profile.id,
        "geography": profile.geography,
        "industry": profile.industry,
        "scenario": profile.scenario,
        "human_study": profile.human_study,
        "synthetic_study": profile.synthetic_study,
        "verdict": profile.verdict,
        "metadata": profile.extra_data,
    }


def _needs_survey_study_metrics_persist(survey: Survey, profile: TestLabProfile) -> bool:
    """True if question-level data exists but verdict / embedded metrics are not fully persisted yet."""
    rep = survey.test_suite_report if isinstance(survey.test_suite_report, dict) else None
    if not rep:
        return False
    qc = rep.get("question_comparisons")
    if not isinstance(qc, list) or len(qc) == 0:
        return False
    verdict = profile.verdict if isinstance(profile.verdict, dict) else {}
    if str(verdict.get("source") or "").lower() == "manual":
        return False
    if str(verdict.get("source") or "").lower() != "rule-based":
        return True
    if survey.directional_alignment is None:
        return True
    sm = rep.get("study_metrics")
    if not isinstance(sm, dict):
        return True
    return False


def _serialize_test_lab_profile(survey_id: str, profile: TestLabProfile) -> dict[str, Any]:
    return {
        "survey_id": survey_id,
        "profile_id": profile.id,
        "geography": profile.geography,
        "industry": profile.industry,
        "scenario": profile.scenario,
        "human_study": profile.human_study or {},
        "synthetic_study": profile.synthetic_study or {},
        "verdict": profile.verdict or {},
        "metadata": profile.extra_data or {},
        "created_at": profile.created_at.isoformat() if profile.created_at else None,
        "updated_at": profile.updated_at.isoformat() if profile.updated_at else None,
    }


@router.get("/test-lab/profiles/batch")
async def get_test_lab_profiles_batch(survey_ids: str, db: Session = Depends(get_db)):
    """
    Fetch multiple Test Lab profiles in one round-trip (reduces dashboard latency).
    Query: survey_ids=comma-separated survey UUIDs (max 80).
    """
    raw = [x.strip() for x in (survey_ids or "").split(",") if x.strip()]
    if not raw:
        raise HTTPException(status_code=400, detail="survey_ids is required (comma-separated survey ids)")
    id_list = list(dict.fromkeys(raw))
    if len(id_list) > 80:
        raise HTTPException(status_code=400, detail="Too many survey_ids (max 80)")

    surveys = {s.id: s for s in db.query(Survey).filter(Survey.id.in_(id_list)).all()}
    profiles_list = db.query(TestLabProfile).filter(TestLabProfile.survey_id.in_(id_list)).all()
    profile_by_id: dict[str, TestLabProfile] = {p.survey_id: p for p in profiles_list}

    for sid in id_list:
        if sid not in surveys:
            continue
        if sid not in profile_by_id:
            p = TestLabProfile(survey_id=sid)
            db.add(p)
            profile_by_id[sid] = p
    db.flush()

    changed_any = False
    for sid in id_list:
        survey = surveys.get(sid)
        profile = profile_by_id.get(sid)
        if not survey or not profile:
            continue
        if _ensure_profile_defaults(profile, survey):
            changed_any = True
    if changed_any:
        db.commit()
        for sid in id_list:
            p = profile_by_id.get(sid)
            if p:
                db.refresh(p)

    metrics_changed = False
    for sid in id_list:
        survey = surveys.get(sid)
        profile = profile_by_id.get(sid)
        if not survey or not profile:
            continue
        if not _needs_survey_study_metrics_persist(survey, profile):
            continue
        rep = survey.test_suite_report if isinstance(survey.test_suite_report, dict) else None
        qc = rep.get("question_comparisons") if rep else None
        if isinstance(qc, list) and qc:
            _sync_survey_study_metrics(survey, db, qc)
            metrics_changed = True
    if metrics_changed:
        db.commit()
        for sid in id_list:
            s = surveys.get(sid)
            if s:
                db.refresh(s)
            p = profile_by_id.get(sid)
            if p:
                db.refresh(p)

    out: dict[str, Any] = {}
    for sid in id_list:
        survey = surveys.get(sid)
        profile = profile_by_id.get(sid)
        if not survey or not profile:
            continue
        out[sid] = _serialize_test_lab_profile(sid, profile)
    return out


@router.get("/test-lab/profile/{survey_id}")
async def get_test_lab_profile(survey_id: str, db: Session = Depends(get_db)):
    survey = db.query(Survey).filter(Survey.id == survey_id).first()
    if not survey:
        raise HTTPException(status_code=404, detail="Survey not found")

    profile = db.query(TestLabProfile).filter(TestLabProfile.survey_id == survey_id).first()
    if not profile:
        profile = TestLabProfile(survey_id=survey_id)
        db.add(profile)
        db.flush()

    if _ensure_profile_defaults(profile, survey):
        db.add(profile)
        db.commit()
        db.refresh(profile)

    if _needs_survey_study_metrics_persist(survey, profile):
        rep = survey.test_suite_report if isinstance(survey.test_suite_report, dict) else None
        qc = rep.get("question_comparisons") if rep else None
        if isinstance(qc, list) and qc:
            _sync_survey_study_metrics(survey, db, qc)
            db.add(survey)
            db.add(profile)
            db.commit()
            db.refresh(profile)
            db.refresh(survey)

    return _serialize_test_lab_profile(survey_id, profile)


@router.post("/test-lab/lead-capture/{survey_id}")
async def capture_test_lab_lead(
    survey_id: str, payload: LeadCapturePayload, db: Session = Depends(get_db)
):
    survey = db.query(Survey).filter(Survey.id == survey_id).first()
    if not survey:
        raise HTTPException(status_code=404, detail="Survey not found")

    lead = TestLabLead(
        survey_id=survey_id,
        name=payload.name.strip(),
        company_name=payload.company_name.strip(),
        email=str(payload.email).strip().lower(),
        consent=payload.consent,
        source=payload.source.strip() if payload.source else "view_detailed_comparison",
        extra_data=sanitize_for_json(payload.metadata),
    )
    db.add(lead)
    db.commit()
    db.refresh(lead)
    logger.info(
        "Captured Test Lab lead for humans@synthetic-people.ai: %s (%s) survey=%s",
        lead.email,
        lead.company_name,
        survey_id,
    )
    return {
        "message": "Lead captured successfully",
        "lead_id": lead.id,
        "survey_id": survey_id,
        "email_delivery_target": "humans@synthetic-people.ai",
    }


@router.post("/test-lab/verdict/{survey_id}/generate")
async def generate_test_lab_verdict_llm(survey_id: str, db: Session = Depends(get_db)):
    """
    Reserved for the LLM verdict layer: compare human vs SP insights and persist verdict.

    System prompt contract: `backend.verdict_llm_contract` (placeholder until Pranjal finalizes).
    Until wired to an LLM provider, this returns 501; use POST …/test-lab/profile/{id} to set verdict manually.
    """
    survey = db.query(Survey).filter(Survey.id == survey_id).first()
    if not survey:
        raise HTTPException(status_code=404, detail="Survey not found")
    raise HTTPException(
        status_code=501,
        detail=(
            "LLM verdict generation is not enabled yet. "
            "See backend.verdict_llm_contract for the prompt contract. "
            "Until implemented, set verdict via POST /api/validation/test-lab/profile/{survey_id}."
        ),
    )


@router.get("/test-lab/metrics")
async def get_test_lab_metrics(db: Session = Depends(get_db)):
    surveys = db.query(Survey).all()
    validated_surveys = [s for s in surveys if s.validation_status == "VALIDATED"]
    profiles = db.query(TestLabProfile).all()

    tests_conducted = len(validated_surveys)
    accuracies = [float(s.accuracy_score) for s in validated_surveys if s.accuracy_score is not None]
    avg_similarity = (sum(accuracies) / len(accuracies)) if accuracies else 0.0

    alignments = []
    scenario_counts: dict[str, int] = {}
    industry_counts: dict[str, int] = {}
    for s in validated_surveys:
        report = s.test_suite_report if isinstance(s.test_suite_report, dict) else {}
        alignment = _compute_directional_alignment(report.get("question_comparisons") or [])
        if alignment is not None:
            alignments.append(alignment)
    survey_ids = {s.id for s in surveys}
    for p in profiles:
        if p.survey_id not in survey_ids:
            continue
        if p.scenario:
            scenario_counts[p.scenario] = scenario_counts.get(p.scenario, 0) + 1
        if p.industry:
            industry_counts[p.industry] = industry_counts.get(p.industry, 0) + 1

    avg_directional_alignment = (sum(alignments) / len(alignments)) if alignments else 0.0
    return {
        "tests_conducted": tests_conducted,
        "avg_similarity": max(0.0, min(1.0, avg_similarity)),
        "avg_directional_alignment": max(0.0, min(1.0, avg_directional_alignment)),
        "scenarios_covered": {
            "count": len(scenario_counts),
            "mix": scenario_counts,
        },
        "industries_covered": {
            "count": len(industry_counts),
            "mix": industry_counts,
        },
    }
